#Include "PROTHEUS.CH"

USER FUNCTION F040FCR()
	//ALERT('PONTO DE ENTRADA F040CR CHAMADO COM SUCESSO!')
	//Reclock("SE1",.F.)	
	//	E1_HIST := 'PE F040FCR OK'
	//MsUnlock()
			
	U_REPLICADADOS('FIN',{'SE1'},1)
		
RETURN