#Include "PROTHEUS.CH"

USER FUNCTION FA050FIN()
			
	U_REPLICADADOS('FIN',{'SE2'},1)
	
	//U_REPLICADADOS('FIN',{'FIV'},1)
	
	//U_REPLICADADOS('FIN',{'FIW'},1)
	
	//U_REPLICADADOS('FIN',{'FJV'},1)
		
RETURN

USER FUNCTION F022GRA()

	U_REPLICADADOS('FIN',{'FIV'},1)
	
	U_REPLICADADOS('FIN',{'FIW'},1)
	
	U_REPLICADADOS('FIN',{'FJV'},1)

RETURN